feat: download tfplan on apply

diff --git a/.github/workflows/on-merge-group.yaml b/.github/workflows/on-merge-group.yaml
--- a/.github/workflows/on-merge-group.yaml
+++ b/.github/workflows/on-merge-group.yaml
@@ -12,7 +12,6 @@ jobs:
     permissions: {}
     steps: [{ run: exit 1 }]
     needs:
-      - changes
       - terraform-lint
       - terraform-apply
 
@@ -40,4 +39,39 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
-      - run: echo "Terraform Apply"
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
+        with:
+          aqua_version: v2.50.0
+
+      - name: Extract PR number
+        id: pr-number
+        run: |
+          pr_number=$(echo "$GITHUB_REF" | sed -n 's#refs/heads/gh-readonly-queue/.*/pr-\([0-9]*\)-.*#\1#p')
+          if [[ -z "$pr_number" ]]; then
+            echo "Could not extract PR number from ref: $GITHUB_REF"
+            exit 1
+          fi
+          echo "Original PR Number: $pr_number"
+          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
+      - name: Download Terraform Plan
+        uses: dawidd6/action-download-artifact@v9
+        with:
+          name: tfplan-${{ matrix.target }}
+          workflow_search: true
+          pr: ${{ steps.pr-number.outputs.pr_number }}
+          path: terraform/${{ matrix.target }}
+
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
+        with:
+          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
+          service_account: ${{ vars.GCLOUD_PLAN_SA }}
+
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Plan & PR Comment
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: tfcmt apply --var 'target:${{ matrix.target }}' -- terraform apply -no-color tfplan
